/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'emotional-lightning',
    path: '/emotional-lightning',
    component: 'layout.base$view.emotional-lightning',
    meta: {
      title: 'emotional-lightning',
      i18nKey: 'route.emotional-lightning',
      icon: 'cil:bolt-circle',
      order: 2
    }
  },
    {
    name: 'concentration-shield',
    path: '/concentration-shield',
    component: 'layout.base$view.concentration-shield',
    meta: {
      title: 'concentration-shield',
      i18nKey: 'route.concentration-shield',
      order: 3
    }
  },
   {
    name: 'bullying-firewall',
    path: '/bullying-firewall',
    component: 'layout.base$view.bullying-firewall',
    meta: {
      title: 'bullying-firewall',
      i18nKey: 'route.bullying-firewall',
      order: 4
    }
  },
  {
    name: 'relationship-umbrella',
    path: '/relationship-umbrella',
    component: 'layout.base$view.relationship-umbrella',
    meta: {
      title: 'relationship-umbrella',
      i18nKey: 'route.relationship-umbrella',
      order: 5
    }
  }
];
