name: Deploy to Aliyun Docker

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
 sync-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check commit message
      run: |
        if [[ "${{ github.event.head_commit.message }}" == *"#release#"* ]]; then
          echo "RELEASE=true" >> $GITHUB_ENV
        else
          echo "RELEASE=false" >> $GITHUB_ENV
        fi
    # 检出代码
    - name: Checkout code
      if: env.RELEASE == 'true'
      uses: actions/checkout@v3
      with:
        path: 'front-web' 
  
    # 设置 SSH 密钥以便进行远程连接
    - name: Set up SSH
      if: env.RELEASE == 'true'
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 添加远程主机的公钥到 known_hosts
    - name: Add SSH host key to known_hosts
      if: env.RELEASE == 'true'
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 101.200.160.131 >> ~/.ssh/known_hosts || true
        chmod 644 ~/.ssh/known_hosts

    # 上传源代码到服务器，并排除 .git 目录
    - name: Upload source code to server (excluding .git)
      if: env.RELEASE == 'true'
      run: |
        rsync -av --exclude='.git' --exclude='Model' --exclude='.github' ./front-web/ root@101.200.160.131:/workspace/deploy/blog-zhjs/

        
    # 部署到服务器
    - name: Deploy Docker containers to server
      if: env.RELEASE == 'true'
      run: |
        # 启用错误检查，确保命令失败时会中止并报告错误
        set -e
        ssh -vT root@101.200.160.131 << 'EOF'
          # 切换到应用目录
          cd /workspace/deploy/blog-zhjs/
          # 设置环境变量 DATE_TAG
          export DATE_TAG=$(date +%Y%m%d)
          # 关闭容器
          docker-compose stop
          # 删除容器
          docker-compose down
          # 构建并启动 Docker 容器，并输出更多调试信息
          docker-compose up -d --build  # 强制构建并启动容器
          # 对空间进行自动清理
          docker system prune -a -f
          # 检查 Docker 容器状态
          docker ps -a
        EOF